### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by rejuvyesh**

### CODE REVIEW

**Comment by MaximeBouton** [comment]
Shouldn't this : 
```julia 
function run_env_server(ip, port, prob::Union{MDP, POMDP}; fully_observable=!isa(prob, POMDP))
    if fully_observable
        env = MDPEnvironment(prob)
    else
        env = POMDPEnvironment(prob)
    end
   # stuff 
end
```

be replaced by 

```julia
function run_env_server(ip, port, prob::MDP)
    env = MDPEnvironment(prob)
    # stuff
end

function run_env_server(ip, port, prob::POMDP)
    env = POMDPEnvironment(prob)
    # stuff
end
```

**Review by MaximeBouton — COMMENTED** [review]
looks good, I have a suggestion in the comments on using multiple dispatch rather than a if statement

**Comment by rejuvyesh** [comment]
I think the reason we did it that way was because we wanted to be able to treat a POMDP problem as an MDP environment (as people often do in Deep RL). Basically observations are states.

**Comment by MaximeBouton** [comment]
I think it still offers this possibility if we just rewrite it using multiple dispatch instead of Union?
There is a k-markov wrapper (state = last k obs) for POMDPs now as well.

**Comment by rejuvyesh** [comment]
Yeah. You can potentially wrap the problem into whatever environment you prefer and run the server with the environment instead.

**Comment by rejuvyesh** [comment]
How about now?

**Pull request merged**
